apiVersion: v1
kind: ConfigMap
metadata:
  name: earlyvet-configmap
data:
  MYSQL_HOST: host.minikube.internal
  MYSQL_USER: auth_user
  MYSQL_DB: auth
  MYSQL_PORT: "3306"
  NEXT_PUBLIC_SENSOR_SERVICE: "http://sensorserver.com"